id: P009584
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-19 20:39:19.971509
source_metadata:
  id: bdr:W8LS19051
  title: བོད་ཀྱི་སྲོལ་རྒྱུན་འཚེམ་བུའི་ཤེས་བྱ་རླབས་ཀྱི་ཕྲེང་བ།
  author: ''
  volumes:
    c6e9d86c579b42a396bb2a0bc606e9d9:
      image_group_id: I8LS19053
      title: ''
      volume_number: 1
      total_pages: 212
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
